const $=id=>document.getElementById(id);
const state={lat:28.6139,lon:77.209,city:"New Delhi, India",unit:"C",w:null,a:null,chart:null};
const WMO={0:["Clear sky","☀"],1:["Mainly clear","🌤"],2:["Partly cloudy","⛅"],3:["Overcast","☁"],45:["Fog","🌫"],48:["Rime fog","🌫"],51:["Light drizzle","🌦"],53:["Drizzle","🌦"],55:["Heavy drizzle","🌧"],56:["Freezing drizzle","🌧"],57:["Heavy freezing drizzle","🌧"],61:["Light rain","🌦"],63:["Rain","🌧"],65:["Heavy rain","🌧"],66:["Freezing rain","🌧"],67:["Heavy freezing rain","🌧"],71:["Light snow","🌨"],73:["Snow","❄"],75:["Heavy snow","❄"],77:["Snow grains","❄"],80:["Rain showers","🌦"],81:["Rain showers","🌧"],82:["Heavy rain showers","⛈"],85:["Snow showers","🌨"],86:["Heavy snow showers","❄"],95:["Thunderstorm","⛈"],96:["Thunderstorm + hail","⛈"],99:["Heavy thunderstorm + hail","⛈"]};
const cv=v=>state.unit==="C"?v:v*9/5+32, temp=v=>Math.round(cv(v))+"°";
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(r.status);return r.json()}
function idx(arr){let n=Date.now(),bi=0,bd=1e30;arr.time.forEach((t,i)=>{const d=Math.abs(new Date(t)-n);if(d<bd){bd=d;bi=i}});return bi}
function status(t){$("status").textContent=t}
function dew(t,r){const A=17.62,B=243.12,g=A*t/(B+t)+Math.log(r/100);return B*g/(A-g)}
function rainAnim(on){const el=$("rain");if(!on){el.classList.remove("on");el.innerHTML="";return}if(el.children.length){el.classList.add("on");return}for(let i=0;i<45;i++){const x=document.createElement("i");x.className="drop";x.style.left=Math.random()*100+"%";x.style.animationDuration=(.65+Math.random()*1.15)+"s";x.style.animationDelay=-(Math.random()*1.5)+"s";el.appendChild(x)}el.classList.add("on")}
function tip(c,d){const p=d.precipitation_probability_max[0]||0;if(p>=65)return`Rain chance is ${Math.round(p)}% today — carry an umbrella.`;if(c.wind_speed_10m>=25)return`Winds are around ${Math.round(c.wind_speed_10m)} km/h — expect a breezier day.`;if(d.uv_index_max[0]>=7)return`UV index peaks near ${d.uv_index_max[0].toFixed(0)} — sun protection is a good idea.`;return`Conditions are ${(WMO[c.weather_code]||["stable"])[0].toLowerCase()} with a high near ${temp(d.temperature_2m_max[0])}.`}
function setAtmosphere(weatherClass){
  const wrap = $("skyRain");
  const layers = [
    wrap.querySelector(".rain-far"),
    wrap.querySelector(".rain-mid"),
    wrap.querySelector(".rain-near")
  ];
  layers.forEach(layer => layer.innerHTML = "");

  if(weatherClass === "rain"){
    const counts = [55, 75, 48];
    counts.forEach((count, layerIndex) => {
      for(let i=0;i<count;i++){
        const d=document.createElement("i");
        d.className="rain-streak";
        d.style.left=`${Math.random()*115-7}%`;
        d.style.height=`${layerIndex===0 ? 42+Math.random()*42 : layerIndex===1 ? 68+Math.random()*55 : 96+Math.random()*78}px`;
        d.style.animationDuration=`${layerIndex===0 ? 1.55+Math.random()*1.35 : layerIndex===1 ? .95+Math.random()*.9 : .62+Math.random()*.62}s`;
        d.style.animationDelay=`-${Math.random()*2.2}s`;
        d.style.opacity=`${layerIndex===0 ? .25+Math.random()*.3 : layerIndex===1 ? .35+Math.random()*.45 : .45+Math.random()*.55}`;
        layers[layerIndex].appendChild(d);
      }
    });
  }
}

async function load(lat,lon,city){status("Fetching live weather…");const p=new URLSearchParams({latitude:lat,longitude:lon,timezone:"auto",current:"temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,snowfall,weather_code,cloud_cover,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m",hourly:"temperature_2m,precipitation_probability,weather_code,visibility,uv_index",daily:"weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,uv_index_max,precipitation_probability_max"});const a=new URLSearchParams({latitude:lat,longitude:lon,timezone:"auto",hourly:"us_aqi,pm2_5,pm10,nitrogen_dioxide,ozone"});try{const[w,air]=await Promise.all([get("https://api.open-meteo.com/v1/forecast?"+p),get("https://air-quality-api.open-meteo.com/v1/air-quality?"+a)]);Object.assign(state,{lat,lon,city,w, a:air});render();status("Live data · "+(w.timezone_abbreviation||w.timezone))}catch(e){console.error(e);status("Could not load live data. Check your connection.")}}
function render(){const w=state.w,c=w.current,d=w.daily,h=w.hourly,a=state.a.hourly,i=idx(h),[desc,icon]=WMO[c.weather_code]||["Unknown","•"];const rain=[61,63,65,80,81,82].includes(c.weather_code);const night = Number(c.is_day) === 0;
 const weatherClass = rain ? "rain" : (c.weather_code>=71&&c.weather_code<=86 ? "snow" : (c.weather_code>=1&&c.weather_code<=3 ? "cloud" : "clear"));
 document.body.className = `${weatherClass} ${night ? "night" : "day"}`;
 setAtmosphere(weatherClass);$("place").textContent=state.city;$("icon").textContent=icon;$("temp").textContent=Math.round(cv(c.temperature_2m));$("cond").textContent=desc;$("feels").textContent="Feels like "+temp(c.apparent_temperature);$("hi").textContent=temp(d.temperature_2m_max[0]);$("lo").textContent=temp(d.temperature_2m_min[0]);$("wind").textContent=Math.round(c.wind_speed_10m)+" km/h";$("hum").textContent=Math.round(c.relative_humidity_2m)+"%";$("pressure").textContent=Math.round(c.surface_pressure)+" hPa";$("vis").textContent=(h.visibility[i]/1000).toFixed(1)+" km";$("uv").textContent=(h.uv_index[i]??d.uv_index_max[0]).toFixed(1);$("rainChance").textContent=(h.precipitation_probability[i]??d.precipitation_probability_max[0])+"%";$("cloud").textContent=c.cloud_cover+"%";$("dew").textContent=temp(dew(c.temperature_2m,c.relative_humidity_2m));$("dir").textContent=Math.round(c.wind_direction_10m)+"°";$("gust").textContent=Math.round(c.wind_gusts_10m)+" km/h";$("rainNow").textContent=Number(c.rain||0).toFixed(1)+" mm";$("snow").textContent=Number(c.snowfall||0).toFixed(1)+" cm";$("rise").textContent=new Date(d.sunrise[0]).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});$("set").textContent=new Date(d.sunset[0]).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});const sr=new Date(d.sunrise[0]),ss=new Date(d.sunset[0]);$("sunbar").style.width=Math.max(0,Math.min(100,(Date.now()-sr)/(ss-sr)*100))+"%";$("updated").textContent="Updated "+new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});$("tip").textContent=tip(c,d);renderHours(h);renderForecast(d);renderChart(h);renderAir(a);rainAnim(rain)}
function renderHours(h){const s=idx(h);let out="";for(let k=0;k<12;k++){const j=Math.min(s+k,h.time.length-1),it=WMO[h.weather_code[j]]||["","•"],dt=new Date(h.time[j]);out+=`<div class="hour"><small>${k===0?"Now":dt.toLocaleTimeString([], {hour:"numeric"})}</small><div>${it[1]}</div><strong>${temp(h.temperature_2m[j])}</strong><em>${h.precipitation_probability[j]||0}% rain</em></div>`}$("hours").innerHTML=out}
function renderForecast(d){$("forecast").innerHTML=d.time.map((t,i)=>{const [desc,icon]=WMO[d.weather_code[i]]||["Unknown","•"],day=i===0?"Today":i===1?"Tomorrow":new Date(t).toLocaleDateString([], {weekday:"short"});return`<div class="frow"><div class="day">${day}</div><div class="ico">${icon}</div><div class="desc">${desc}</div><div class="ftemp">${temp(d.temperature_2m_max[i])}<i>${temp(d.temperature_2m_min[i])}</i></div></div>`}).join("")}
function renderChart(h){const s=idx(h),lab=[],dat=[];for(let k=0;k<24;k++){const j=Math.min(s+k,h.time.length-1);lab.push(new Date(h.time[j]).toLocaleTimeString([], {hour:"numeric"}));dat.push(Number(h.temperature_2m[j].toFixed(1)))}if(state.chart)state.chart.destroy();state.chart=new Chart($("chart"),{type:"line",data:{labels:lab,datasets:[{data:dat,borderColor:"rgba(145,169,255,.95)",backgroundColor:"rgba(145,169,255,.07)",fill:true,borderWidth:2,pointRadius:0,tension:.34}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{displayColors:false,callbacks:{label:c=>" "+temp(c.raw)}}},scales:{x:{grid:{color:"rgba(255,255,255,.035)"},ticks:{color:"#70798a",font:{size:9},maxTicksLimit:8}},y:{grid:{color:"rgba(255,255,255,.04)"},ticks:{color:"#70798a",font:{size:9},callback:v=>temp(v)}}}}})}
function renderAir(a){const i=idx(a),q=Math.round(a.us_aqi[i]||0),lab=q<=50?"Good":q<=100?"Moderate":q<=150?"Unhealthy for sensitive groups":q<=200?"Unhealthy":"Very unhealthy";$("aqn").textContent=q||"--";$("aqlevel").textContent=lab;$("aqbadge").textContent=lab;$("aqmeter").style.width=Math.min(100,Math.max(2,q/300*100))+"%";$("pm25").textContent=Number(a.pm2_5[i]||0).toFixed(1);$("pm10").textContent=Number(a.pm10[i]||0).toFixed(1);$("no2").textContent=Number(a.nitrogen_dioxide[i]||0).toFixed(1);$("o3").textContent=Number(a.ozone[i]||0).toFixed(1)}
async function searchCity(q){if(!q.trim())return;status("Searching locations…");try{const d=await get("https://geocoding-api.open-meteo.com/v1/search?name="+encodeURIComponent(q)+"&count=5&language=en&format=json");if(!d.results?.length){status("No location found.");return}const s=$("suggestions");s.innerHTML=d.results.map((r,i)=>`<button data-i="${i}">${r.name}${r.admin1?", "+r.admin1:""}${r.country?", "+r.country:""}</button>`).join("");s.classList.add("open");s.querySelectorAll("button").forEach(b=>b.onclick=()=>{const r=d.results[+b.dataset.i];s.classList.remove("open");$("q").value="";load(r.latitude,r.longitude,`${r.name}${r.country?", "+r.country:""}`)})}catch(e){status("Location search failed.")}}
$("search").onsubmit=e=>{e.preventDefault();searchCity($("q").value)};$("unit").onclick=()=>{state.unit=state.unit==="C"?"F":"C";if(state.w)render()};$("loc").onclick=()=>{if(!navigator.geolocation)return;status("Requesting your location…");navigator.geolocation.getCurrentPosition(p=>load(p.coords.latitude,p.coords.longitude,"Your location"),()=>status("Location access was denied or unavailable."))};document.addEventListener("click",e=>{if(!e.target.closest(".search"))$("suggestions").classList.remove("open")});
load(state.lat,state.lon,state.city);